import { type StandardEvent } from './presets.js';

export type Framework = 'express' | 'nextjs' | 'standalone';
export type Database = 'sqlite' | 'postgres' | 'mysql' | 'clickhouse';

export interface TemplateContext {
  framework: Framework;
  database: Database;
  presetName: string;
  events: StandardEvent[];
  apiKey: string;
  port: number;
}

// ─── Database adapter snippets ────────────────────────

function adapterImport(db: Database): string {
  const map: Record<Database, string> = {
    sqlite: "const { createAnalyticsServer, SQLiteAdapter } = require('@trackpaw/server');",
    postgres: "const { createAnalyticsServer } = require('@trackpaw/server');\nconst { PostgresAdapter } = require('@trackpaw/server/adapters');",
    mysql: "const { createAnalyticsServer } = require('@trackpaw/server');\nconst { MySQLAdapter } = require('@trackpaw/server/adapters');",
    clickhouse: "const { createAnalyticsServer } = require('@trackpaw/server');\nconst { ClickHouseAdapter } = require('@trackpaw/server/adapters');",
  };
  return map[db]!;
}

function adapterImportESM(db: Database): string {
  const map: Record<Database, string> = {
    sqlite: "import { createAnalyticsServer, SQLiteAdapter } from '@trackpaw/server';",
    postgres: "import { createAnalyticsServer } from '@trackpaw/server';\nimport { PostgresAdapter } from '@trackpaw/server/adapters';",
    mysql: "import { createAnalyticsServer } from '@trackpaw/server';\nimport { MySQLAdapter } from '@trackpaw/server/adapters';",
    clickhouse: "import { createAnalyticsServer } from '@trackpaw/server';\nimport { ClickHouseAdapter } from '@trackpaw/server/adapters';",
  };
  return map[db]!;
}

function adapterInstance(db: Database): string {
  const map: Record<Database, string> = {
    sqlite: `new SQLiteAdapter({\n    filename: './analytics.db',\n  })`,
    postgres: `new PostgresAdapter({\n    connectionString: process.env.DATABASE_URL || 'postgresql://localhost:5432/trackpaw',\n  })`,
    mysql: `new MySQLAdapter({\n    host: process.env.DB_HOST || 'localhost',\n    port: Number(process.env.DB_PORT) || 3306,\n    database: process.env.DB_NAME || 'trackpaw',\n    user: process.env.DB_USER || 'root',\n    password: process.env.DB_PASSWORD || '',\n  })`,
    clickhouse: `new ClickHouseAdapter({\n    url: process.env.CLICKHOUSE_URL || 'http://localhost:8123',\n    database: process.env.CLICKHOUSE_DB || 'trackpaw',\n  })`,
  };
  return map[db]!;
}

// ─── Server deps by database ──────────────────────────

export function serverDeps(db: Database): string[] {
  const base = ['@trackpaw/server'];
  const map: Record<Database, string[]> = {
    sqlite: [],
    postgres: ['pg'],
    mysql: ['mysql2'],
    clickhouse: ['@clickhouse/client'],
  };
  return [...base, ...map[db]!];
}

export function trackerDeps(): string[] {
  return ['@trackpaw/tracker'];
}

export function allDeps(db: Database): string[] {
  return [...serverDeps(db), ...trackerDeps()];
}

// ─── Events file ──────────────────────────────────────

export function generateEventsFile(ctx: TemplateContext): string {
  const lines = ctx.events.map((e) => {
    const propsType =
      e.properties.length > 0 ? `{ ${e.properties.map((p) => `${p}: string`).join('; ')} }` : 'Record<string, never>';
    return `  /** ${e.description} */\n  '${e.name}': ${propsType};`;
  });

  return `// Auto-generated by trackpaw init (${ctx.presetName} preset)
// Customize these events to match your product.

export interface TrackpawEvents {
${lines.join('\n\n')}
}

export const EVENT_NAMES = [
${ctx.events.map((e) => `  '${e.name}',`).join('\n')}
] as const;
`;
}

// ─── Express template ─────────────────────────────────

function expressTemplate(ctx: TemplateContext): string {
  return `const express = require('express');
${adapterImport(ctx.database)}

const app = express();
const PORT = process.env.PORT || ${ctx.port};

// ─── Analytics Setup ─────────────────────────────────
const analytics = createAnalyticsServer({
  adapter: ${adapterInstance(ctx.database)},
  apiKey: process.env.TRACKPAW_API_KEY || '${ctx.apiKey}',
  cors: { origin: true },
  privacy: { ipAnonymization: true },
});

analytics.migrate().then(() => {
  console.log('Trackpaw analytics ready');
});

app.use('/analytics', analytics.router);

// ─── Your routes ─────────────────────────────────────
app.get('/', (_req, res) => {
  res.send('Hello! Trackpaw analytics is running at /analytics/v1/health');
});

app.listen(PORT, () => {
  console.log(\`Server running at http://localhost:\${PORT}\`);
});
`;
}

// ─── Next.js template ─────────────────────────────────

function nextjsServerTemplate(ctx: TemplateContext): string {
  return `${adapterImportESM(ctx.database)}

let instance: ReturnType<typeof createAnalyticsServer> | null = null;
let initialized = false;

export function getAnalyticsServer() {
  if (!instance) {
    instance = createAnalyticsServer({
      adapter: ${adapterInstance(ctx.database)},
      apiKey: process.env.TRACKPAW_API_KEY || '${ctx.apiKey}',
    });
  }
  return instance;
}

export async function ensureInitialized() {
  if (!initialized) {
    const server = getAnalyticsServer();
    await server.migrate();
    initialized = true;
  }
}
`;
}

function nextjsRouteTemplate(): string {
  return `import { type NextRequest, NextResponse } from 'next/server';
import { getAnalyticsServer, ensureInitialized } from '@/lib/analytics-server';

async function handler(req: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  await ensureInitialized();
  const analytics = getAnalyticsServer();
  const { path } = await params;
  const subpath = '/' + path.join('/');

  // Forward the request to the analytics router
  const url = new URL(req.url);
  url.pathname = '/v1' + subpath;

  const headers: Record<string, string> = {};
  req.headers.forEach((value, key) => {
    headers[key] = value;
  });

  const body = ['GET', 'HEAD'].includes(req.method) ? undefined : await req.text();

  const response = await new Promise<{ status: number; headers: Record<string, string>; body: string }>(
    (resolve) => {
      const mockRes = {
        statusCode: 200,
        headers: {} as Record<string, string>,
        setHeader(key: string, value: string) { this.headers[key] = value; },
        status(code: number) { this.statusCode = code; return this; },
        json(data: unknown) {
          resolve({ status: this.statusCode, headers: this.headers, body: JSON.stringify(data) });
        },
        send(data: string) {
          resolve({ status: this.statusCode, headers: this.headers, body: data });
        },
      };

      const mockReq = {
        method: req.method,
        url: url.pathname + url.search,
        path: '/v1' + subpath,
        headers,
        body: body ? JSON.parse(body) : undefined,
        query: Object.fromEntries(url.searchParams),
        ip: req.headers.get('x-forwarded-for') || '127.0.0.1',
      };

      analytics.router(mockReq as any, mockRes as any, () => {
        resolve({ status: 404, headers: {}, body: 'Not found' });
      });
    }
  );

  return new NextResponse(response.body, {
    status: response.status,
    headers: response.headers,
  });
}

export const GET = handler;
export const POST = handler;
`;
}

function nextjsTrackerTemplate(ctx: TemplateContext): string {
  return `import { Trackpaw } from '@trackpaw/tracker';

let tracker: ReturnType<typeof Trackpaw.init> | null = null;

export function getTracker() {
  if (!tracker && typeof window !== 'undefined') {
    tracker = Trackpaw.init({
      endpoint: '/api/analytics',
      apiKey: process.env.NEXT_PUBLIC_TRACKPAW_KEY || '${ctx.apiKey}',
      autoTrack: { pageViews: false },
    });
  }
  return tracker;
}
`;
}

// ─── Standalone template ──────────────────────────────

function standaloneTemplate(ctx: TemplateContext): string {
  return `const express = require('express');
${adapterImport(ctx.database)}

const app = express();
const PORT = process.env.PORT || ${ctx.port};

const analytics = createAnalyticsServer({
  adapter: ${adapterInstance(ctx.database)},
  apiKey: process.env.TRACKPAW_API_KEY || '${ctx.apiKey}',
  cors: { origin: true },
  privacy: { ipAnonymization: true },
});

analytics.migrate().then(() => {
  console.log('Trackpaw analytics ready');
});

// Mount all analytics routes at root
app.use(analytics.router);

app.listen(PORT, () => {
  console.log(\`Trackpaw analytics server at http://localhost:\${PORT}/v1/health\`);
});
`;
}

// ─── Tracker snippet ──────────────────────────────────

function trackerSnippet(ctx: TemplateContext): string {
  const endpoint =
    ctx.framework === 'nextjs' ? '/api/analytics' : `http://localhost:${ctx.port}/analytics`;

  return `<!-- Add this to your HTML, or import in your JS/TS app -->
<script type="module">
  import { Trackpaw } from 'https://esm.sh/@trackpaw/tracker';

  const trackpaw = Trackpaw.init({
    endpoint: '${endpoint}',
    apiKey: '${ctx.apiKey}',
    autoTrack: {
      pageViews: true,
      clicks: true,
      forms: true,
    },
  });
</script>
`;
}

// ─── Env file ─────────────────────────────────────────

function envTemplate(ctx: TemplateContext): string {
  const lines = [`TRACKPAW_API_KEY=${ctx.apiKey}`, `PORT=${ctx.port}`];

  if (ctx.database === 'postgres') {
    lines.push('DATABASE_URL=postgresql://localhost:5432/trackpaw');
  } else if (ctx.database === 'mysql') {
    lines.push('DB_HOST=localhost', 'DB_PORT=3306', 'DB_NAME=trackpaw', 'DB_USER=root', 'DB_PASSWORD=');
  } else if (ctx.database === 'clickhouse') {
    lines.push('CLICKHOUSE_URL=http://localhost:8123', 'CLICKHOUSE_DB=trackpaw');
  }

  if (ctx.framework === 'nextjs') {
    lines.push(`NEXT_PUBLIC_TRACKPAW_KEY=${ctx.apiKey}`);
  }

  return lines.join('\n') + '\n';
}

// ─── Public API ───────────────────────────────────────

export interface GeneratedFile {
  path: string;
  content: string;
  description: string;
}

export function generateFiles(ctx: TemplateContext): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // .env
  files.push({
    path: '.env',
    content: envTemplate(ctx),
    description: 'Environment variables',
  });

  // Events file
  files.push({
    path: ctx.framework === 'nextjs' ? 'lib/trackpaw-events.ts' : 'trackpaw-events.ts',
    content: generateEventsFile(ctx),
    description: `Standard events (${ctx.presetName} preset)`,
  });

  if (ctx.framework === 'express') {
    files.push({
      path: 'trackpaw-server.js',
      content: expressTemplate(ctx),
      description: 'Express analytics server',
    });
    files.push({
      path: 'trackpaw-tracker.html',
      content: trackerSnippet(ctx),
      description: 'Client-side tracker snippet',
    });
  } else if (ctx.framework === 'nextjs') {
    files.push({
      path: 'lib/analytics-server.ts',
      content: nextjsServerTemplate(ctx),
      description: 'Next.js server singleton',
    });
    files.push({
      path: 'app/api/analytics/[...path]/route.ts',
      content: nextjsRouteTemplate(),
      description: 'Next.js API route handler',
    });
    files.push({
      path: 'lib/analytics.ts',
      content: nextjsTrackerTemplate(ctx),
      description: 'Client-side tracker singleton',
    });
  } else {
    files.push({
      path: 'trackpaw-server.js',
      content: standaloneTemplate(ctx),
      description: 'Standalone analytics server',
    });
    files.push({
      path: 'trackpaw-tracker.html',
      content: trackerSnippet(ctx),
      description: 'Client-side tracker snippet',
    });
  }

  return files;
}
